branches:
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^hotfix\/.*$/

sudo: false

language: ruby
rvm: 2.4.2

cache:
  - apt
  - bundler

before_script:
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then export APP_ENV=production; fi
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then export APP_ENV=staging; fi

script:
  - echo "BRANCH is $TRAVIS_BRANCH"
  - echo "APP_ENV is $APP_ENV"
  - echo "TRAVIS_PULL_REQUEST is $TRAVIS_PULL_REQUEST"
  - echo "TRAVIS_COMMIT_MESSAGE is $TRAVIS_COMMIT_MESSAGE"
  - bundle exec middleman contentful
  - bundle exec middleman build --verbose
  - APP_ENV='development' bundle exec rake test # tests run as development, regardless of the destination

after_success:
  - if [[ "$TRAVIS_COMMIT_MESSAGE" == *FORCE_SYNC* ]]; then FORCE="--force"; fi
  - echo "FORCE is $FORCE"
  - RESULT="no sync done (default)"
  - if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then bundle exec middleman s3_sync $FORCE && RESULT="synced ok to production"; fi
  - if [[ "$TRAVIS_BRANCH" = "develop" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then bundle exec middleman s3_sync $FORCE && RESULT="synced ok to staging"; fi
  - echo "Sync result is $RESULT"

notifications:
  email:
    on_success: never
  slack: # see: https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications
    rooms:
      secure: 1ub00lCcP/3qD9IFy+6NZWx8oQoFE/6UPq3a+TrRDzbulRKlWsIa5+maU/Loz2Av9ahhIMHBaQk2JFmQpUHD3V4X4/ATwl1LjEcf3LhmDphs5YkGGzSmEwQujHaUigWeP3qnkRkVQDvn/8MUzOP+02/wuocCqkaEeNO6GUDnpRErd2iFTLGRR2CYiUFt9z0gM6+4dPjr8wOfxyP3jdmaRfPLixlV9hSJ2RHr3XsSIcvPemltpt5NX3aAMV5CTGEuL7NeOUpo5CoG06iEXmXoXRD+6oHu5NkZWFnZc0b1k432HMJxSM+sF6ZwdGu/hzR6qd7NgEHF1WbmHx84KEKLhR095E19sg4E4zK7qoK+bXMiycOgEZ+tmnzbsAFrLqE0XqMqfeJ7+16uTeRwyI/s74HQfwGfzI9rNXR05uJIMog+4y3QjgRUAAduMwXJUtBPEJXDSMwSg435uYeUGbNhUHsVNNLth6dB6o6Itho7f1AB59aE5SUh2vWt2mETZ6lvv8ijfKDcmi9Gs4E/oYl0SEUDkpU0JJ7vr8uW1YsfOYkv+e7feNYv2qdvwdju4bXvJkkMX4Sq0UJdAy6aOVM4I82MVxbA+Y+d8NdihfgTbJ3MY0RMirzMiOEz5w/lqsNNqvRmfoeJb/udxGOJtjE4AAc8lJ2AcaLEX2LSz7buCNA=
