name: Lint Code Base

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  push:
    branches-ignore:
      - 'master'

###############
# Set the Job #
###############
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      # -------- Github Checkout
      - uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v2.2.0
        env:
          VALIDATE_ALL_CODEBASE: true # TEMP: Will set to FALSE to only validates edited files in the future.
